### ISSUE TITLE
注册发信域名目前是写死的，需要提取为配置文件

### ISSUE THREAD

**Issue by zhuweiyou** [mtdhb/api#10]
https://github.com/mtdhb/api/blob/59768e1adce740ab1ccf87329d859254ce240528/src/main/resources/registerMailTemplate.html#L9-L12

@huangdenghe

**Comment by huangdenghe** [comment]
邮件模板属于资源文件，而资源文件其实也可以视为配置文件的一种，要修改注册地址直接修改模板文件就好，没必要特地提取至另外的配置文件。此处修改后续会在 README.md 中补充说明。

**Comment by zhuweiyou** [comment]
OK，补充后 close 吧
