### ISSUE TITLE
cookie_use_count 中 status 为 1 或 3 是什么状态？

### ISSUE THREAD

**Issue by iola1999** [mtdhb/api#12]

**Comment by zhuweiyou** [comment]
https://github.com/mtdhb/api/blob/058a44d83f7d9c8319a994ebf186c55e9883e53a/src/main/java/com/mtdhb/api/constant/e/CookieUseStatus.java#L1-L18

**Comment by iola1999** [comment]
每天清理的时候似乎不会删除这两种状态的记录，这会导致可用cookies减少吗？

**Comment by huangdenghe** [comment]
@iola1999 不会 ，就算什么都不删除也不会导致可用 cookie 减少
