### ISSUE TITLE
有个不成熟的想法

### ISSUE THREAD

**Issue by asurada-gsx** [mtdhb/api#13]
可否构造不存在的用户，或者使用其他用户的微信号，来领取
- 饿了么无法直接拿到用户的微信号和手机号，是通过openid+手机号来关联用户
- 所以可否通过暴力尝试appid，罗列其他用户的appid，输入手机号，来作为小号使用

- 以上

**Comment by zhuweiyou** [comment]
在今年之前，我们采用的就是这种方案，随机伪造 openid，美团和饿了么都可以通过！
你可以查看一下 mtdhb/old 老早的提交记录。

后来美团和饿了么，都针对我们进行了更新，所以此法失效了。
