### ISSUE TITLE
不能运行在jdk 10

### ISSUE THREAD

**Issue by yuzmb** [mtdhb/api#14]
![image](https://user-images.githubusercontent.com/13777514/45441584-f3e45080-b6f1-11e8-856e-3c9f453d8b1d.png)
否则会报好多莫名其妙的错误，我不懂java
运行在jdk1.8就没事了

**Comment by zhuweiyou** [comment]
按照 README 说的环境要求来吧。
如果你机器有 jdk 10 ，再装 8 也不影响吧，指一下环境变量。
